# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [9]:
!git clone "https://github.com/aryanks692/Flyrank-ai-Notebook.git"

%cd Flyrank-ai-Notebook

import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")
df.head()

fatal: destination path 'Flyrank-ai-Notebook' already exists and is not an empty directory.
/content/Flyrank-ai-Notebook

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [1]:
# This cell is for CODE (numbers, a query, a check).
#Decision:

#Which content pages should an editor prioritize for refresh before they lose significant search traffic?

#Task Type:

#Classification

#Reason:

#The model predicts whether a content page is likely to decline, allowing editors to intervene before performance drops further.
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

In [10]:
# This cell is for CODE (numbers, a query, a check).
## 2. Target or proxy

##**Target:** `is_declining_label`

##The target is to predict whether a content page is declining in performance.

##The target label is created from the observed `trend_direction` column in the starter dataset. Pages with a `trend_direction` of **"down"** are labeled as 1 (declining), while all other pages are labeled as 0 (not declining).

##This target represents an observed outcome in the dataset and is used only as the prediction label, not as an input feature.

# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All
# Create the target label

df["is_declining_label"] = (
    df["trend_direction"] == "down"
).astype(int)

# Display the target
df[["trend_direction", "is_declining_label"]].head(10)

  trend_direction  is_declining_label
0            down                   1
1            down                   1
2            down                   1
3          stable                   0
4            down                   1
5            down                   1
6            down                   1
7          stable                   0
8            down                   1
9            down                   1

## 3. Success metric

*One metric you can defend. What number means 'good'?*

In [11]:
# This cell is for CODE (numbers, a query, a check).
## 3. Success metric

##**Success Metric:** Precision@50

##Precision@50 measures how many of the top 50 pages predicted as declining are actually declining.

##This metric is appropriate because content editors can only refresh a limited number of pages. A high Precision@50 means the model identifies the most important pages for editors to review first.

##Secondary evaluation metrics such as ROC-AUC and Average Precision can also be used to measure the model's overall classification performance.
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Show the proportion of each class
df["is_declining_label"].value_counts(normalize=True)

is_declining_label
1    0.542067
0    0.457933
Name: proportion, dtype: float64

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [12]:
# This cell is for CODE (numbers, a query, a check).
## 4. The unit of analysis, as a real dataframe

##One row in the dataset represents one content page (content item).

##Each row contains historical information about that page, including search performance, traffic, engagement, ranking position, and content characteristics. These features are used to help predict whether the page is likely to decline in performance.
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Display the first five rows of the dataset
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,is_declining_label
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4,1
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7,1
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9,1
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8,0
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7,1

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

In [13]:
# This cell is for CODE (numbers, a query, a check).
## 5. Why ML beats a fixed rule here

##A simple rule, such as refreshing every page with a CTR below 1%, is not enough because content performance depends on many interacting factors. Metrics such as impressions, clicks, average position, engagement rate, content age, and search volume all influence whether a page is likely to decline.

##Machine learning can learn patterns from these multiple signals and identify pages at risk more effectively than a single fixed rule. The model is intended to support content editors in making better prioritization decisions rather than replacing human judgment.
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
# Display all available columns
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct', 'is_declining_label']

## Self-check

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.